# Generated by Django 5.1.6 on 2025-04-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Status',
            new_name='status',
        ),
    ]
