# Generated by Django 5.1.6 on 2025-04-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_status_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
